/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.jsonc --include-runtime=false --strict-vars=false --env-interface=WorkerEnv` (hash: 8d38ebaf88a99703155e8ccbdf624f7d)
interface __BaseEnv_WorkerEnv {
	MEDIA: R2Bucket;
	DB: D1Database;
	NOCANVA_AUTH_MODE: string;
	BETTER_AUTH_URL: string;
	NOCANVA_MCP_RESOURCE: string;
	NOCANVA_SUPPORT_EMAIL: string;
	NOCANVA_APPROVAL_MODE: string;
	NOCANVA_WORKSPACE_ID: string;
	BETTER_AUTH_SECRET: string;
	GOOGLE_CLIENT_ID: string;
	GOOGLE_CLIENT_SECRET: string;
	NOCANVA_APP_TOKEN: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./worker/index");
	}
	interface Env extends __BaseEnv_WorkerEnv {}
}
interface WorkerEnv extends __BaseEnv_WorkerEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "NOCANVA_AUTH_MODE" | "BETTER_AUTH_URL" | "NOCANVA_MCP_RESOURCE" | "NOCANVA_SUPPORT_EMAIL" | "NOCANVA_APPROVAL_MODE" | "NOCANVA_WORKSPACE_ID" | "BETTER_AUTH_SECRET" | "GOOGLE_CLIENT_ID" | "GOOGLE_CLIENT_SECRET" | "NOCANVA_APP_TOKEN">> {}
}
