/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.mcp.jsonc --include-runtime=false --strict-vars=false --env-interface=McpWorkerEnv mcp/worker-env.d.ts` (hash: 8fef0bbcbc6202c9b6c8e38839edc6bc)
interface __BaseEnv_McpWorkerEnv {
	BROWSER: BrowserRun;
	NOCANVA_BASE_URL: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./worker");
	}
	interface Env extends __BaseEnv_McpWorkerEnv {}
}
interface McpWorkerEnv extends __BaseEnv_McpWorkerEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "NOCANVA_BASE_URL">> {}
}
