/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.mcp.jsonc --include-runtime=false --strict-vars=false --env-interface=McpWorkerEnv mcp/worker-env.d.ts` (hash: 0de86cbc2bf77617b4d1c982318348b6)
interface __BaseEnv_McpWorkerEnv {
	BROWSER: BrowserRun;
	NOCANVA_BASE_URL: string;
	NOCANVA_AUTH_ISSUER: string;
	NOCANVA_MCP_RESOURCE: string;
	NOCANVA_APP_TOKEN: string;
	NOCANVA_APP: Fetcher /* nocanva-app */;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./worker");
	}
	interface Env extends __BaseEnv_McpWorkerEnv {}
}
interface McpWorkerEnv extends __BaseEnv_McpWorkerEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "NOCANVA_BASE_URL" | "NOCANVA_AUTH_ISSUER" | "NOCANVA_MCP_RESOURCE" | "NOCANVA_APP_TOKEN">> {}
}
